### ISSUE TITLE
Document how to configure "keystore" for SCDF and Skipper

### ISSUE THREAD

**Issue by sabbyanandan** [pivotal-cf/docs-spring-cloud-dataflow-k8s#17]
> Oded Shopen  2:24 AM
One issue I'm facing is how to transfer the keystore contents to the `application.yaml`. The security section here: https://docs.pivotal.io/scdf-k8s/0-1/configuring-installation-values.html redirects you to the SCDF documentation, but that expects you to run on your own machine and not as pods on Kubernetes. So, just adding the path to the keystore file will not work because that path doesn't exist inside the pod. I guess I could add it as a volume mount to the pod but I think this should be documented.
Caused by: java.io.FileNotFoundException: /home/odedia/scdf/dataflow.keystore (No such file or directory)

Resolved with this:
```
kubectl create configmap keystore --from-file=/home/odedia/scdf/dataflow.keystore
Then modified ./apps/data-flow/kustomize/overlays/dev/deployment-patch.yaml as follows:
metadata:
  name: scdf-server
spec:
  template:
    spec:
      containers:
      - name: scdf-server
        volumeMounts:
          - name: database
            mountPath: /etc/secrets/database
            readOnly: true
          - name: keystore 
            mountPath: /etc/secrets/keystore
            readOnly: true
      imagePullSecrets:
      - name: scdf-image-regcred
      volumes:
        - name: database
          secret:
            secretName: postgresql
            items:
            - key: postgresql-password
              path: database-password
        - name: keystore
          configMap:
            name: keystore
```

And then `application.yml` defines: key-store: "/etc/secrets/keystore/dataflow.keystore"
